### PR TITLE
Treat empty string same as missing name parameter

### PR DESCRIPTION
**Pull request by Xarthisius**
See https://github.com/whole-tale/ngx-dashboard/pull/55#issuecomment-728155174 and https://github.com/whole-tale/ngx-dashboard/pull/55#issuecomment-729815378

### CODE REVIEW

**Comment by hategan** [comment]
Did it allow renaming to empty strings while failing at os.rename()?

**Comment by Xarthisius** [comment]
> Did it allow renaming to empty strings while failing at os.rename()?

I haven't checked but I think it would have returned 400 too, which is not wrong. This is only a cosmetic change to treat "" as None.

**Comment by hategan** [comment]
> > Did it allow renaming to empty strings while failing at os.rename()?
> 
> I haven't checked but I think it would have returned 400 too, which is not wrong. This is only a cosmetic change to treat "" as None.

I was curious what motivated this. But at this point the discussion is becoming bigger than the change, so probably not worth it.

**Comment by Xarthisius** [comment]
> > > Did it allow renaming to empty strings while failing at os.rename()?
> > 
> > 
> > I haven't checked but I think it would have returned 400 too, which is not wrong. This is only a cosmetic change to treat "" as None.
> 
> I was curious what motivated this. But at this point the discussion is becoming bigger than the change, so probably not worth it.

In theory I'm an academic. I'm happy to discuss anything at any depth :D

**Pull request merged**
